spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/funerariadb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:false}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:validate}

app.storage.provider=local
app.storage.local.root-path=${APP_STORAGE_LOCAL_ROOT_PATH:/data/storage}
app.storage.local.public-base-url=${APP_STORAGE_LOCAL_PUBLIC_BASE_URL:http://localhost:8081/files/}
app.web.cors.enabled=${APP_WEB_CORS_ENABLED:false}
app.web.cors.allowed-origin-patterns=${APP_WEB_CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}

app.bootstrap.admin.enabled=${APP_BOOTSTRAP_ADMIN_ENABLED:true}
app.bootstrap.admin.email=${APP_BOOTSTRAP_ADMIN_EMAIL:admin@funeraria.local}
app.bootstrap.admin.password=${APP_BOOTSTRAP_ADMIN_PASSWORD:Admin123!}
app.bootstrap.admin.first-name=${APP_BOOTSTRAP_ADMIN_FIRST_NAME:Admin}
app.bootstrap.admin.last-name=${APP_BOOTSTRAP_ADMIN_LAST_NAME:Funeraria}
