create sequence addresses_seq start with 1 increment by 50;
create sequence brands_seq start with 1 increment by 50;
create sequence categories_seq start with 1 increment by 50;
create sequence cities_seq start with 1 increment by 50;
create sequence confirmation_tokens_seq start with 1 increment by 50;
create sequence death_causes_seq start with 1 increment by 50;
create sequence deceased_seq start with 1 increment by 50;
create sequence genders_seq start with 1 increment by 50;
create sequence income_details_seq start with 1 increment by 50;
create sequence incomes_seq start with 1 increment by 50;
create sequence mobile_numbers_seq start with 1 increment by 50;
create sequence provinces_seq start with 1 increment by 50;
create sequence receipt_types_seq start with 1 increment by 50;
create sequence relationships_seq start with 1 increment by 50;
create sequence roles_seq start with 1 increment by 50;
create sequence users_seq start with 1 increment by 50;

create table addresses (
    block_street integer,
    city_id bigint,
    id bigint not null,
    supplier_id bigint,
    user_id bigint,
    apartment varchar(90),
    flat varchar(90),
    street_name varchar(90) not null,
    primary key (id)
);

create table affiliates (
    birth_date date not null,
    deceased boolean default false,
    dni integer not null,
    start_date date,
    gender_id bigint,
    id bigint generated by default as identity,
    relationship_id bigint,
    user_id bigint,
    last_name varchar(70) not null,
    first_name varchar(100) not null,
    primary key (id),
    constraint index_dni unique (dni)
);

create table brands (
    id bigint not null,
    name varchar(95) not null,
    web_page varchar(95),
    primary key (id)
);

create table categories (
    id bigint not null,
    name varchar(75) not null,
    description varchar(255),
    primary key (id)
);

create table cities (
    id bigint not null,
    province_id bigint,
    zip_code varchar(10) not null,
    name varchar(100) not null,
    primary key (id)
);

create table confirmation_tokens (
    expiry_date timestamp(6) with time zone,
    id bigint not null,
    user_id bigint not null,
    token varchar(100) not null,
    primary key (id)
);

create table death_causes (
    id bigint not null,
    name varchar(150) not null,
    primary key (id)
);

create table deceased (
    affiliated boolean default false,
    birth_date date not null,
    death_date date not null,
    dni integer not null,
    address_id bigint unique,
    death_cause_id bigint,
    gender_id bigint,
    id bigint not null,
    register_date timestamp(6),
    relationship_id bigint,
    user_id bigint,
    last_name varchar(100) not null,
    first_name varchar(150) not null,
    primary key (id)
);

create table funeral (
    tax numeric(5,2),
    total_amount numeric(11,2) not null,
    deceased_id bigint unique,
    funeral_date timestamp(6) not null,
    id bigint generated by default as identity,
    plan_id bigint,
    receipt_type_id bigint,
    register_date timestamp(6),
    receipt_number varchar(50) not null unique,
    receipt_series varchar(50) not null,
    primary key (id)
);

create table genders (
    id bigint not null,
    name varchar(75) not null,
    primary key (id)
);

create table income_details (
    purchase_price numeric(8,2) not null,
    quantity integer not null,
    sale_price numeric(8,2) not null,
    id bigint not null,
    income_id bigint,
    item_id bigint,
    primary key (id)
);

create table incomes (
    deleted boolean not null,
    tax numeric(5,2),
    total_amount numeric(8,2) default 0,
    id bigint not null,
    income_date timestamp(6),
    last_modified_date timestamp(6),
    receipt_number bigint not null,
    receipt_series bigint not null,
    receipt_type_id bigint,
    supplier_id bigint,
    user_id bigint,
    user_modified_id bigint,
    primary key (id)
);

create table items (
    item_height numeric(8,2),
    item_length numeric(10,2),
    item_width numeric(8,2),
    price numeric(10,2),
    stock integer,
    brand_id bigint,
    category_id bigint,
    id bigint generated by default as identity,
    name varchar(85) not null,
    code varchar(95) unique,
    description varchar(255),
    item_image_link varchar(255),
    primary key (id)
);

create table items_plan (
    quantity integer not null,
    item_id bigint not null,
    plan_id bigint not null,
    primary key (item_id, plan_id)
);

create table mobile_numbers (
    id bigint not null,
    supplier_id bigint,
    user_id bigint,
    mobile_number varchar(255) not null,
    primary key (id)
);

create table plans (
    price numeric(11,2),
    profit_percentage numeric(9,2) not null,
    id bigint generated by default as identity,
    name varchar(100) not null,
    description text,
    image_url varchar(255),
    primary key (id)
);

create table provinces (
    code31662 varchar(5) not null,
    id bigint not null,
    name varchar(90) not null,
    primary key (id)
);

create table receipt_types (
    id bigint not null,
    name varchar(75) not null,
    primary key (id)
);

create table refresh_tokens (
    expiry_date timestamp(6) with time zone not null,
    id bigint generated by default as identity,
    issued_at timestamp(6) with time zone not null,
    last_used_at timestamp(6) with time zone,
    refresh_count bigint,
    revoked_at timestamp(6) with time zone,
    user_device_id bigint not null unique,
    version bigint,
    token_hash varchar(64) not null unique,
    primary key (id)
);

create table relationships (
    id bigint not null,
    name varchar(60) not null,
    primary key (id)
);

create table roles (
    id bigint not null,
    name varchar(255) check ((name in ('ROLE_ADMIN', 'ROLE_USER'))),
    primary key (id)
);

create table suppliers (
    id bigint generated by default as identity,
    nif varchar(80) not null unique,
    email varchar(90) not null,
    web_page varchar(90),
    name varchar(100) not null,
    primary key (id)
);

create table user_devices (
    is_refresh_active boolean,
    id bigint generated by default as identity,
    last_seen_at timestamp(6) with time zone,
    token_version bigint,
    user_id bigint not null unique,
    version bigint,
    fingerprint_hash varchar(64) not null,
    device_id varchar(255) not null,
    device_type varchar(255),
    last_ip_address varchar(255),
    primary key (id)
);

create table user_role (
    role_id bigint not null,
    user_id bigint not null,
    primary key (role_id, user_id)
);

create table users (
    active boolean not null,
    enabled boolean,
    start_date date,
    id bigint not null,
    first_name varchar(90) not null,
    last_name varchar(90) not null,
    email varchar(150) not null,
    encrypted_password varchar(255) not null,
    primary key (id),
    constraint index_email unique (email)
);

alter table addresses add constraint FK9fkb8qaj71tiyr9htkmn7r8y5 foreign key (city_id) references cities;
alter table addresses add constraint FK9mieednkuq1gb3nvrv26orys foreign key (supplier_id) references suppliers;
alter table addresses add constraint FK1fa36y2oqhao3wgg2rw1pi459 foreign key (user_id) references users;
alter table affiliates add constraint FKjf4wf83cbba0wmdhe3t55tk2g foreign key (gender_id) references genders;
alter table affiliates add constraint FKmh0fqelfje5vqaf1objx6sie5 foreign key (relationship_id) references relationships;
alter table affiliates add constraint FKo5w1h272ne70p0lwox7g5o4ek foreign key (user_id) references users;
alter table cities add constraint FKcf2ndxcsekl26rrkb9egbhq20 foreign key (province_id) references provinces;
alter table confirmation_tokens add constraint FKhpuw37a1pqxfb6ya1nv5lm4ga foreign key (user_id) references users;
alter table deceased add constraint FKlt9wn4jhtdeu5rcurwq5276sc foreign key (death_cause_id) references death_causes;
alter table deceased add constraint FKmx6163qxb83wxwmyoaf0acwdk foreign key (relationship_id) references relationships;
alter table deceased add constraint FKfn67g54d7ensxkwl2b4j930rq foreign key (user_id) references users;
alter table deceased add constraint FKmglqxaclj2j0rejk9c6tbdmtx foreign key (gender_id) references genders;
alter table deceased add constraint FKtpc550hprdkrkuxv6k7wvalkp foreign key (address_id) references addresses;
alter table funeral add constraint FKj0ldjaa445km9ceh1lknowcvm foreign key (deceased_id) references deceased;
alter table funeral add constraint FK6j3adsr59f7chf84phciiodfe foreign key (plan_id) references plans;
alter table funeral add constraint FK9e2nts4lmf75jx66s1en2j7ev foreign key (receipt_type_id) references receipt_types;
alter table income_details add constraint FK4g874l1xwbscsneof8kl1epu8 foreign key (income_id) references incomes;
alter table income_details add constraint FK70614vfd3ahrnwkhiy6x9qqga foreign key (item_id) references items;
alter table incomes add constraint FKfq6qeso6vbt9wu7dyhnx8tpu9 foreign key (user_id) references users;
alter table incomes add constraint FKlqoxrkg51o94pvv4rd4owtap2 foreign key (user_modified_id) references users;
alter table incomes add constraint FKlb2i3l4dk0x4cnbytopax3y44 foreign key (receipt_type_id) references receipt_types;
alter table incomes add constraint FKeshwph9rii3iov116aigr3tea foreign key (supplier_id) references suppliers;
alter table items add constraint FKi0gnxi21mo1gmbl3q2cqvpx69 foreign key (brand_id) references brands;
alter table items add constraint FKjcdcde7htb3tyjgouo4g9xbmr foreign key (category_id) references categories;
alter table items_plan add constraint FK43ifqmevwngsvdid5hjsr1r49 foreign key (item_id) references items;
alter table items_plan add constraint FKf70dle9i8xtigtdja8lykt6rl foreign key (plan_id) references plans;
alter table mobile_numbers add constraint FKmftvwt8uvojgv4j3v6mny943f foreign key (supplier_id) references suppliers;
alter table mobile_numbers add constraint FKncbfyrlgcd1p8648n352fk0so foreign key (user_id) references users;
alter table refresh_tokens add constraint FKlmv25kf7q0rc52xdwb8he1iil foreign key (user_device_id) references user_devices;
alter table user_devices add constraint FKik0n080vvur1fvdxtygwkt3m4 foreign key (user_id) references users;
alter table user_role add constraint FKt7e7djp752sqn6w22i6ocqy6q foreign key (role_id) references roles;
alter table user_role add constraint FKj345gk1bovqvfame88rcx7yyx foreign key (user_id) references users;
